name: ByeBoletos
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  sqflite:
  path_provider:
  fluttericon: ^1.0.7
  email_validator: '^1.0.0'
  brasil_fields: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


